site_name: Barrel-DB pour aof17
theme_dir: cinder
pages:
    - Home: index.md
    - Barrel:
        - 'Concepts': barrel/concepts.md
        - 'Patterns': barrel/patterns.md
        - 'Python': barrel/python.md
        - 'Javascript': barrel/javascript.md
        - 'Ruby': barrel/ruby.md
        - 'Admin': barrel/admin.md
    - A propos: apropos.md
