site_name: Barrel-DB pour aof17
theme_dir: cinder
pages:
    - Home: index.md
    - Barrel:
        - 'API Rest': barrel/rest.md
        - 'Python': barrel/python.md
        - 'Elixir': barrel/elixir.md
        - 'Admin': barrel/admin.md
    - A propos: apropos.md
